# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 04:28
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='reply',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
