# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180315_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='user_id',
            new_name='user',
        ),
    ]
