# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180321_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='num_replies',
            field=models.IntegerField(null=True),
        ),
    ]
