# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180409_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='num_replies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
