# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import oauth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=40)),
                ('username', models.CharField(error_messages={'blank': 'You must enter a username.', 'duplicate_username': 'That username already exists.', 'invalid': 'Username is invalid. Usernames should only contain letters, numbers or underscores.', 'max_length': 'Usernames must be less than 15 characters long.'}, max_length=15, unique=True, validators=[oauth.models.usernameValidator()])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
